config/routes.rb
Rails.application.routes.draw do
  root 'home#nocache'

  controller 'home' do
    get 'nocache'
    get 'public'
    get 'private'
    get 'shared_only'
    get 'bit_of_ajax'
    post 'api_example_1'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery except: ['api_example_1']

  def nocache
    expires_now
  end

  def public
    expires_in 5.minutes, public: true
  end

  def private
    expires_in 5.minutes, private: true
  end

  def shared_only
    expires_in 0.seconds, public: true, 's-maxage': 5.minutes
  end

  def bit_of_ajax
  end

  def api_example_1
    #expires_in 1.hour, public: false

    # let's pretend it's super expensive operation
    sleep 2.seconds

    render json: { result: params[:a].to_i + params[:b].to_i } if
      stale?(last_modified: Date.today, etag: [params[:a], params[:b]], template: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/bit_of_ajax.html.erb
<% content_for :heading do %>
    AJAX tricks
<% end %>

<div ng-app="app" ng-controller="Calculator">
  <form ng-submit="result = calc(a, b)">
    <p>a: <input ng-model="a" required></p>
    <p>b: <input ng-model="b" required></p>
    <p>result: {{result}}</p>
    <input type="submit" value="Calculate">
  </form>
</div>

app/views/home/nocache.html.erb
<% content_for :heading do %>
    Cache-Control: no-cache, private
<% end %>

Not supposed to be cahced anywhere. For continuously changing data.

app/views/home/private.html.erb
<% content_for :heading do %>
    Cache-Control: private, max-age=300
<% end %>

For content that can be cached but is too unique to specific user. Will be cached client side only.

app/views/home/public.html.erb
<% content_for :heading do %>
    Cache-Control: public, max-age=300
<% end %>

For content that applies to all users, maybe is expensive to generate or download. Will be cached by both server
side cache and in users browser cache.

app/views/home/shared_only.html.erb
<% content_for :heading do %>
    Cache-Control: max-age=0, public, s-maxage=300
<% end %>

For content that applies to all users, maybe is expensive to generate. Will be cached server side only. Browsers
will keep sending requests on each reload but rack-cache will respond with <code>304 Not Modified</code> thus saving
network bandwidth. This also leaves move control over invalidation.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails and rack-cache demo</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<div class="page-header">
  <h1>Gentle intro to client and server side HTTP caching</h1>
</div>

<ul class="nav nav-pills">
  <li role="presentation"><%= link_to 'No cache', nocache_path %></li>
  <li role="presentation"><%= link_to 'Public', public_path %></li>
  <li role="presentation"><%= link_to 'Private', private_path %></li>
  <li role="presentation"><%= link_to 'Shared only', shared_only_path %></li>
  <li role="presentation"><%= link_to 'Some AJAX shenanigans', bit_of_ajax_path %></li>
</ul>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield :heading %></h3>
  </div>

  <div class="panel-body">
    <%= yield %>
  </div>

  <div class="panel-footer">
    Time this page was generated: <strong><%= time_tag Time.now %></strong>
  </div>
</div>

</body>
</html>